In [1]:
import numpy as np
def actf(x):
    return 1/(1+np.exp(-x))#시그모이드 함수
def d_actf(x):
    return x*(1-x)#시그모이드 함수를 미분 

In [6]:
# y = wx + b
w=np.array([[1,2,3],
            [3,4,5]])
x=np.array([[4,5],
            [6,7],
           [8,9]])
w.dot(x)



array([[40, 46],
       [76, 88]])

In [3]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])
in_n = 3#3개입력 층
h_n = 6 #은닉층
out_n = 1# 출력 층
np.random.seed(5)
# 초기값
w0 = 2*np.random.random((in_n,h_n))-1
w1 = 2*np.random.random((h_n,out_n))-1


In [4]:
for i in range(10000):
    l0 = X#1층
    # 순 전 파
    #입력*W0
    net1 =np.dot(l0,w0)
    l1=actf(net1)
    l1[:,-1] = 1#은닉층
    net2 = np.dot(l1,w1)
    l2 = actf(net2)#결과
    #역전파 알고리즘적용
    l2_e = l2-y#오차
    l2_d=l2_e*d_actf(l2)#미분(출력단의 델타값)
    
    l1_e = np.dot(l2_d,w1.T)#은닉 오차
    l1_d=l1_e*d_actf(l1)#미분 (은닉단의 델타값)
    #가중치 변화를 적용
    w1 += -0.2*np.dot(l1.T,l2_d)
    w0 += -0.2*np.dot(l0.T,l1_d)
    if i ==10:
        print(l2)
        print()
    if i ==100:
        print(l2)
        print()
    if i ==1000:
        print(l2)
        print()
    if i ==10000:
        print(l2)
        print()
    
    #print(l2)
print(l2)

[[0.44867697]
 [0.48397079]
 [0.41941189]
 [0.45527361]]

[[0.49810382]
 [0.52553137]
 [0.47556608]
 [0.50256195]]

[[0.46051417]
 [0.52154431]
 [0.50562375]
 [0.52060927]]

[[0.02391914]
 [0.9757925 ]
 [0.97343127]
 [0.03041428]]


In [5]:
y

array([[0],
       [1],
       [1],
       [0]])